//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWCF_Veterinaria
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBVeterinariaEntities : DbContext
    {
        public DBVeterinariaEntities()
            : base("name=DBVeterinariaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Consulta> Consulta { get; set; }
        public virtual DbSet<Det_Consulta> Det_Consulta { get; set; }
        public virtual DbSet<Esp> Esp { get; set; }
        public virtual DbSet<Especialidad> Especialidad { get; set; }
        public virtual DbSet<Mascota> Mascota { get; set; }
        public virtual DbSet<Medicamento> Medicamento { get; set; }
        public virtual DbSet<Ubigeo> Ubigeo { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Veterinario> Veterinario { get; set; }
        public virtual DbSet<vw_VistaConsulta> vw_VistaConsulta { get; set; }
        public virtual DbSet<vw_VistaCliente> vw_VistaCliente { get; set; }
        public virtual DbSet<vw_VistaVeterinario> vw_VistaVeterinario { get; set; }
    
        public virtual int usp_ConsultarCliente(Nullable<int> vcod)
        {
            var vcodParameter = vcod.HasValue ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ConsultarCliente", vcodParameter);
        }
    
        public virtual int usp_ActualizarCliente(Nullable<int> vcod, string vnom, string vape, Nullable<int> vdni, string vidubigeo, string vdireccion, string vtel_cli, Nullable<int> vest_cli, string vsexo, string vemail, string vnum_reg, string vusu_ult_mod)
        {
            var vcodParameter = vcod.HasValue ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(int));
    
            var vnomParameter = vnom != null ?
                new ObjectParameter("vnom", vnom) :
                new ObjectParameter("vnom", typeof(string));
    
            var vapeParameter = vape != null ?
                new ObjectParameter("vape", vape) :
                new ObjectParameter("vape", typeof(string));
    
            var vdniParameter = vdni.HasValue ?
                new ObjectParameter("vdni", vdni) :
                new ObjectParameter("vdni", typeof(int));
    
            var vidubigeoParameter = vidubigeo != null ?
                new ObjectParameter("vidubigeo", vidubigeo) :
                new ObjectParameter("vidubigeo", typeof(string));
    
            var vdireccionParameter = vdireccion != null ?
                new ObjectParameter("vdireccion", vdireccion) :
                new ObjectParameter("vdireccion", typeof(string));
    
            var vtel_cliParameter = vtel_cli != null ?
                new ObjectParameter("vtel_cli", vtel_cli) :
                new ObjectParameter("vtel_cli", typeof(string));
    
            var vest_cliParameter = vest_cli.HasValue ?
                new ObjectParameter("vest_cli", vest_cli) :
                new ObjectParameter("vest_cli", typeof(int));
    
            var vsexoParameter = vsexo != null ?
                new ObjectParameter("vsexo", vsexo) :
                new ObjectParameter("vsexo", typeof(string));
    
            var vemailParameter = vemail != null ?
                new ObjectParameter("vemail", vemail) :
                new ObjectParameter("vemail", typeof(string));
    
            var vnum_regParameter = vnum_reg != null ?
                new ObjectParameter("vnum_reg", vnum_reg) :
                new ObjectParameter("vnum_reg", typeof(string));
    
            var vusu_ult_modParameter = vusu_ult_mod != null ?
                new ObjectParameter("vusu_ult_mod", vusu_ult_mod) :
                new ObjectParameter("vusu_ult_mod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarCliente", vcodParameter, vnomParameter, vapeParameter, vdniParameter, vidubigeoParameter, vdireccionParameter, vtel_cliParameter, vest_cliParameter, vsexoParameter, vemailParameter, vnum_regParameter, vusu_ult_modParameter);
        }
    
        public virtual int usp_EliminarCliente(Nullable<int> vcod)
        {
            var vcodParameter = vcod.HasValue ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarCliente", vcodParameter);
        }
    
        public virtual int usp_InsertarCliente(string vnom, string vape, Nullable<int> vdni, string vidubigeo, string vdireccion, string vtel_cli, string vusu_reg, Nullable<int> vest_cli, string vsexo, string vemail)
        {
            var vnomParameter = vnom != null ?
                new ObjectParameter("vnom", vnom) :
                new ObjectParameter("vnom", typeof(string));
    
            var vapeParameter = vape != null ?
                new ObjectParameter("vape", vape) :
                new ObjectParameter("vape", typeof(string));
    
            var vdniParameter = vdni.HasValue ?
                new ObjectParameter("vdni", vdni) :
                new ObjectParameter("vdni", typeof(int));
    
            var vidubigeoParameter = vidubigeo != null ?
                new ObjectParameter("vidubigeo", vidubigeo) :
                new ObjectParameter("vidubigeo", typeof(string));
    
            var vdireccionParameter = vdireccion != null ?
                new ObjectParameter("vdireccion", vdireccion) :
                new ObjectParameter("vdireccion", typeof(string));
    
            var vtel_cliParameter = vtel_cli != null ?
                new ObjectParameter("vtel_cli", vtel_cli) :
                new ObjectParameter("vtel_cli", typeof(string));
    
            var vusu_regParameter = vusu_reg != null ?
                new ObjectParameter("vusu_reg", vusu_reg) :
                new ObjectParameter("vusu_reg", typeof(string));
    
            var vest_cliParameter = vest_cli.HasValue ?
                new ObjectParameter("vest_cli", vest_cli) :
                new ObjectParameter("vest_cli", typeof(int));
    
            var vsexoParameter = vsexo != null ?
                new ObjectParameter("vsexo", vsexo) :
                new ObjectParameter("vsexo", typeof(string));
    
            var vemailParameter = vemail != null ?
                new ObjectParameter("vemail", vemail) :
                new ObjectParameter("vemail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarCliente", vnomParameter, vapeParameter, vdniParameter, vidubigeoParameter, vdireccionParameter, vtel_cliParameter, vusu_regParameter, vest_cliParameter, vsexoParameter, vemailParameter);
        }
    
        public virtual int usp_ListarClientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ListarClientes");
        }
    
        public virtual int usp_ActualizarMascota(Nullable<int> vcod_mas, Nullable<int> vcod_esp, string vnom_mas, string vnom_cli, string vape_cli, Nullable<int> vcod_cli, byte[] vfoto_mas, string vsexo_mas, string vcolor_mas, Nullable<System.DateTime> vfec_mas, Nullable<int> vest_mascota, string vUsuUlt_Mod)
        {
            var vcod_masParameter = vcod_mas.HasValue ?
                new ObjectParameter("vcod_mas", vcod_mas) :
                new ObjectParameter("vcod_mas", typeof(int));
    
            var vcod_espParameter = vcod_esp.HasValue ?
                new ObjectParameter("vcod_esp", vcod_esp) :
                new ObjectParameter("vcod_esp", typeof(int));
    
            var vnom_masParameter = vnom_mas != null ?
                new ObjectParameter("vnom_mas", vnom_mas) :
                new ObjectParameter("vnom_mas", typeof(string));
    
            var vnom_cliParameter = vnom_cli != null ?
                new ObjectParameter("vnom_cli", vnom_cli) :
                new ObjectParameter("vnom_cli", typeof(string));
    
            var vape_cliParameter = vape_cli != null ?
                new ObjectParameter("vape_cli", vape_cli) :
                new ObjectParameter("vape_cli", typeof(string));
    
            var vcod_cliParameter = vcod_cli.HasValue ?
                new ObjectParameter("vcod_cli", vcod_cli) :
                new ObjectParameter("vcod_cli", typeof(int));
    
            var vfoto_masParameter = vfoto_mas != null ?
                new ObjectParameter("vfoto_mas", vfoto_mas) :
                new ObjectParameter("vfoto_mas", typeof(byte[]));
    
            var vsexo_masParameter = vsexo_mas != null ?
                new ObjectParameter("vsexo_mas", vsexo_mas) :
                new ObjectParameter("vsexo_mas", typeof(string));
    
            var vcolor_masParameter = vcolor_mas != null ?
                new ObjectParameter("vcolor_mas", vcolor_mas) :
                new ObjectParameter("vcolor_mas", typeof(string));
    
            var vfec_masParameter = vfec_mas.HasValue ?
                new ObjectParameter("vfec_mas", vfec_mas) :
                new ObjectParameter("vfec_mas", typeof(System.DateTime));
    
            var vest_mascotaParameter = vest_mascota.HasValue ?
                new ObjectParameter("vest_mascota", vest_mascota) :
                new ObjectParameter("vest_mascota", typeof(int));
    
            var vUsuUlt_ModParameter = vUsuUlt_Mod != null ?
                new ObjectParameter("vUsuUlt_Mod", vUsuUlt_Mod) :
                new ObjectParameter("vUsuUlt_Mod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarMascota", vcod_masParameter, vcod_espParameter, vnom_masParameter, vnom_cliParameter, vape_cliParameter, vcod_cliParameter, vfoto_masParameter, vsexo_masParameter, vcolor_masParameter, vfec_masParameter, vest_mascotaParameter, vUsuUlt_ModParameter);
        }
    
        public virtual int usp_EliminarMascota(Nullable<int> vcod_mas)
        {
            var vcod_masParameter = vcod_mas.HasValue ?
                new ObjectParameter("vcod_mas", vcod_mas) :
                new ObjectParameter("vcod_mas", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarMascota", vcod_masParameter);
        }
    
        public virtual int usp_InsertarMascota(string vnom_mas, string vnom_cli, string vape_cli, Nullable<int> vcod_cli, Nullable<int> vcod_esp, byte[] vfoto_mas, string vsexo_mas, string vcolor_mas, Nullable<System.DateTime> vfec_mas, Nullable<int> vest_mascota)
        {
            var vnom_masParameter = vnom_mas != null ?
                new ObjectParameter("vnom_mas", vnom_mas) :
                new ObjectParameter("vnom_mas", typeof(string));
    
            var vnom_cliParameter = vnom_cli != null ?
                new ObjectParameter("vnom_cli", vnom_cli) :
                new ObjectParameter("vnom_cli", typeof(string));
    
            var vape_cliParameter = vape_cli != null ?
                new ObjectParameter("vape_cli", vape_cli) :
                new ObjectParameter("vape_cli", typeof(string));
    
            var vcod_cliParameter = vcod_cli.HasValue ?
                new ObjectParameter("vcod_cli", vcod_cli) :
                new ObjectParameter("vcod_cli", typeof(int));
    
            var vcod_espParameter = vcod_esp.HasValue ?
                new ObjectParameter("vcod_esp", vcod_esp) :
                new ObjectParameter("vcod_esp", typeof(int));
    
            var vfoto_masParameter = vfoto_mas != null ?
                new ObjectParameter("vfoto_mas", vfoto_mas) :
                new ObjectParameter("vfoto_mas", typeof(byte[]));
    
            var vsexo_masParameter = vsexo_mas != null ?
                new ObjectParameter("vsexo_mas", vsexo_mas) :
                new ObjectParameter("vsexo_mas", typeof(string));
    
            var vcolor_masParameter = vcolor_mas != null ?
                new ObjectParameter("vcolor_mas", vcolor_mas) :
                new ObjectParameter("vcolor_mas", typeof(string));
    
            var vfec_masParameter = vfec_mas.HasValue ?
                new ObjectParameter("vfec_mas", vfec_mas) :
                new ObjectParameter("vfec_mas", typeof(System.DateTime));
    
            var vest_mascotaParameter = vest_mascota.HasValue ?
                new ObjectParameter("vest_mascota", vest_mascota) :
                new ObjectParameter("vest_mascota", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarMascota", vnom_masParameter, vnom_cliParameter, vape_cliParameter, vcod_cliParameter, vcod_espParameter, vfoto_masParameter, vsexo_masParameter, vcolor_masParameter, vfec_masParameter, vest_mascotaParameter);
        }
    
        public virtual ObjectResult<usp_ListarConsultasMascotaFechas_Result> usp_ListarConsultasMascotaFechas(Nullable<int> vcod_mascota, Nullable<System.DateTime> vFechaInicio1, Nullable<System.DateTime> vFechaFin1)
        {
            var vcod_mascotaParameter = vcod_mascota.HasValue ?
                new ObjectParameter("vcod_mascota", vcod_mascota) :
                new ObjectParameter("vcod_mascota", typeof(int));
    
            var vFechaInicio1Parameter = vFechaInicio1.HasValue ?
                new ObjectParameter("vFechaInicio1", vFechaInicio1) :
                new ObjectParameter("vFechaInicio1", typeof(System.DateTime));
    
            var vFechaFin1Parameter = vFechaFin1.HasValue ?
                new ObjectParameter("vFechaFin1", vFechaFin1) :
                new ObjectParameter("vFechaFin1", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarConsultasMascotaFechas_Result>("usp_ListarConsultasMascotaFechas", vcod_mascotaParameter, vFechaInicio1Parameter, vFechaFin1Parameter);
        }
    
        public virtual ObjectResult<usp_ListarConsultasVeterinarioFechas_Result> usp_ListarConsultasVeterinarioFechas(Nullable<int> vcod_veterinario, string vEstado, Nullable<System.DateTime> vFechaInicio, Nullable<System.DateTime> vFechaFin)
        {
            var vcod_veterinarioParameter = vcod_veterinario.HasValue ?
                new ObjectParameter("vcod_veterinario", vcod_veterinario) :
                new ObjectParameter("vcod_veterinario", typeof(int));
    
            var vEstadoParameter = vEstado != null ?
                new ObjectParameter("vEstado", vEstado) :
                new ObjectParameter("vEstado", typeof(string));
    
            var vFechaInicioParameter = vFechaInicio.HasValue ?
                new ObjectParameter("vFechaInicio", vFechaInicio) :
                new ObjectParameter("vFechaInicio", typeof(System.DateTime));
    
            var vFechaFinParameter = vFechaFin.HasValue ?
                new ObjectParameter("vFechaFin", vFechaFin) :
                new ObjectParameter("vFechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarConsultasVeterinarioFechas_Result>("usp_ListarConsultasVeterinarioFechas", vcod_veterinarioParameter, vEstadoParameter, vFechaInicioParameter, vFechaFinParameter);
        }
    
        public virtual ObjectResult<usp_ListarMascotasdeClientesFechas_Result> usp_ListarMascotasdeClientesFechas(Nullable<int> vCod_Cliente, string vEstado2, Nullable<System.DateTime> vFechaInicio3, Nullable<System.DateTime> vFechaFin3)
        {
            var vCod_ClienteParameter = vCod_Cliente.HasValue ?
                new ObjectParameter("vCod_Cliente", vCod_Cliente) :
                new ObjectParameter("vCod_Cliente", typeof(int));
    
            var vEstado2Parameter = vEstado2 != null ?
                new ObjectParameter("vEstado2", vEstado2) :
                new ObjectParameter("vEstado2", typeof(string));
    
            var vFechaInicio3Parameter = vFechaInicio3.HasValue ?
                new ObjectParameter("vFechaInicio3", vFechaInicio3) :
                new ObjectParameter("vFechaInicio3", typeof(System.DateTime));
    
            var vFechaFin3Parameter = vFechaFin3.HasValue ?
                new ObjectParameter("vFechaFin3", vFechaFin3) :
                new ObjectParameter("vFechaFin3", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarMascotasdeClientesFechas_Result>("usp_ListarMascotasdeClientesFechas", vCod_ClienteParameter, vEstado2Parameter, vFechaInicio3Parameter, vFechaFin3Parameter);
        }
    
        public virtual ObjectResult<usp_ListarMascotasPorEspecie_Result> usp_ListarMascotasPorEspecie(Nullable<int> vcodEspecie)
        {
            var vcodEspecieParameter = vcodEspecie.HasValue ?
                new ObjectParameter("vcodEspecie", vcodEspecie) :
                new ObjectParameter("vcodEspecie", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarMascotasPorEspecie_Result>("usp_ListarMascotasPorEspecie", vcodEspecieParameter);
        }
    
        public virtual ObjectResult<usp_ConsultasXAño_Result> usp_ConsultasXAño(Nullable<int> vaño3)
        {
            var vaño3Parameter = vaño3.HasValue ?
                new ObjectParameter("vaño3", vaño3) :
                new ObjectParameter("vaño3", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultasXAño_Result>("usp_ConsultasXAño", vaño3Parameter);
        }
    
        public virtual ObjectResult<usp_TopAtencionesClientesMascotasAño_Result> usp_TopAtencionesClientesMascotasAño(Nullable<int> vaño)
        {
            var vañoParameter = vaño.HasValue ?
                new ObjectParameter("vaño", vaño) :
                new ObjectParameter("vaño", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TopAtencionesClientesMascotasAño_Result>("usp_TopAtencionesClientesMascotasAño", vañoParameter);
        }
    
        public virtual ObjectResult<usp_TopAtencionesMascotasAño_Result> usp_TopAtencionesMascotasAño(Nullable<int> vaño2)
        {
            var vaño2Parameter = vaño2.HasValue ?
                new ObjectParameter("vaño2", vaño2) :
                new ObjectParameter("vaño2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TopAtencionesMascotasAño_Result>("usp_TopAtencionesMascotasAño", vaño2Parameter);
        }
    
        public virtual ObjectResult<usp_TopMedicinasXAño_Result> usp_TopMedicinasXAño(Nullable<int> vaño4)
        {
            var vaño4Parameter = vaño4.HasValue ?
                new ObjectParameter("vaño4", vaño4) :
                new ObjectParameter("vaño4", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TopMedicinasXAño_Result>("usp_TopMedicinasXAño", vaño4Parameter);
        }
    
        public virtual ObjectResult<usp_ResumenConsultasXAño_Result> usp_ResumenConsultasXAño(Nullable<int> vaño3)
        {
            var vaño3Parameter = vaño3.HasValue ?
                new ObjectParameter("vaño3", vaño3) :
                new ObjectParameter("vaño3", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ResumenConsultasXAño_Result>("usp_ResumenConsultasXAño", vaño3Parameter);
        }
    
        public virtual ObjectResult<usp_ListarConsultasMascotaFechas2_Result> usp_ListarConsultasMascotaFechas2(Nullable<int> vcod_mascota, Nullable<System.DateTime> vFechaInicio1, Nullable<System.DateTime> vFechaFin1)
        {
            var vcod_mascotaParameter = vcod_mascota.HasValue ?
                new ObjectParameter("vcod_mascota", vcod_mascota) :
                new ObjectParameter("vcod_mascota", typeof(int));
    
            var vFechaInicio1Parameter = vFechaInicio1.HasValue ?
                new ObjectParameter("vFechaInicio1", vFechaInicio1) :
                new ObjectParameter("vFechaInicio1", typeof(System.DateTime));
    
            var vFechaFin1Parameter = vFechaFin1.HasValue ?
                new ObjectParameter("vFechaFin1", vFechaFin1) :
                new ObjectParameter("vFechaFin1", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarConsultasMascotaFechas2_Result>("usp_ListarConsultasMascotaFechas2", vcod_mascotaParameter, vFechaInicio1Parameter, vFechaFin1Parameter);
        }
    
        public virtual ObjectResult<usp_ListarConsultasMascotaFecha_Result> usp_ListarConsultasMascotaFecha(Nullable<int> vcod_mascota, Nullable<System.DateTime> vFechaInicio1, Nullable<System.DateTime> vFechaFin1)
        {
            var vcod_mascotaParameter = vcod_mascota.HasValue ?
                new ObjectParameter("vcod_mascota", vcod_mascota) :
                new ObjectParameter("vcod_mascota", typeof(int));
    
            var vFechaInicio1Parameter = vFechaInicio1.HasValue ?
                new ObjectParameter("vFechaInicio1", vFechaInicio1) :
                new ObjectParameter("vFechaInicio1", typeof(System.DateTime));
    
            var vFechaFin1Parameter = vFechaFin1.HasValue ?
                new ObjectParameter("vFechaFin1", vFechaFin1) :
                new ObjectParameter("vFechaFin1", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarConsultasMascotaFecha_Result>("usp_ListarConsultasMascotaFecha", vcod_mascotaParameter, vFechaInicio1Parameter, vFechaFin1Parameter);
        }
    
        public virtual ObjectResult<usp_ListarConsultasVeterinarioFecha_Result> usp_ListarConsultasVeterinarioFecha(Nullable<int> vcod_veterinario, string vEstado, Nullable<System.DateTime> vFechaInicio, Nullable<System.DateTime> vFechaFin)
        {
            var vcod_veterinarioParameter = vcod_veterinario.HasValue ?
                new ObjectParameter("vcod_veterinario", vcod_veterinario) :
                new ObjectParameter("vcod_veterinario", typeof(int));
    
            var vEstadoParameter = vEstado != null ?
                new ObjectParameter("vEstado", vEstado) :
                new ObjectParameter("vEstado", typeof(string));
    
            var vFechaInicioParameter = vFechaInicio.HasValue ?
                new ObjectParameter("vFechaInicio", vFechaInicio) :
                new ObjectParameter("vFechaInicio", typeof(System.DateTime));
    
            var vFechaFinParameter = vFechaFin.HasValue ?
                new ObjectParameter("vFechaFin", vFechaFin) :
                new ObjectParameter("vFechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarConsultasVeterinarioFecha_Result>("usp_ListarConsultasVeterinarioFecha", vcod_veterinarioParameter, vEstadoParameter, vFechaInicioParameter, vFechaFinParameter);
        }
    
        public virtual ObjectResult<usp_ListarConsultasVeterinarioFechas2_Result> usp_ListarConsultasVeterinarioFechas2(Nullable<int> vcod_veterinario, string vEstado, Nullable<System.DateTime> vFechaInicio, Nullable<System.DateTime> vFechaFin)
        {
            var vcod_veterinarioParameter = vcod_veterinario.HasValue ?
                new ObjectParameter("vcod_veterinario", vcod_veterinario) :
                new ObjectParameter("vcod_veterinario", typeof(int));
    
            var vEstadoParameter = vEstado != null ?
                new ObjectParameter("vEstado", vEstado) :
                new ObjectParameter("vEstado", typeof(string));
    
            var vFechaInicioParameter = vFechaInicio.HasValue ?
                new ObjectParameter("vFechaInicio", vFechaInicio) :
                new ObjectParameter("vFechaInicio", typeof(System.DateTime));
    
            var vFechaFinParameter = vFechaFin.HasValue ?
                new ObjectParameter("vFechaFin", vFechaFin) :
                new ObjectParameter("vFechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarConsultasVeterinarioFechas2_Result>("usp_ListarConsultasVeterinarioFechas2", vcod_veterinarioParameter, vEstadoParameter, vFechaInicioParameter, vFechaFinParameter);
        }
    
        public virtual ObjectResult<usp_ListarMascotasPorEspecie2_Result> usp_ListarMascotasPorEspecie2(Nullable<int> vcodEspecie)
        {
            var vcodEspecieParameter = vcodEspecie.HasValue ?
                new ObjectParameter("vcodEspecie", vcodEspecie) :
                new ObjectParameter("vcodEspecie", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarMascotasPorEspecie2_Result>("usp_ListarMascotasPorEspecie2", vcodEspecieParameter);
        }
    
        public virtual ObjectResult<usp_ListarMascotasdeClientesFecha_Result> usp_ListarMascotasdeClientesFecha(Nullable<int> vCod_Cliente, string vEstado2, Nullable<System.DateTime> vFechaInicio3, Nullable<System.DateTime> vFechaFin3)
        {
            var vCod_ClienteParameter = vCod_Cliente.HasValue ?
                new ObjectParameter("vCod_Cliente", vCod_Cliente) :
                new ObjectParameter("vCod_Cliente", typeof(int));
    
            var vEstado2Parameter = vEstado2 != null ?
                new ObjectParameter("vEstado2", vEstado2) :
                new ObjectParameter("vEstado2", typeof(string));
    
            var vFechaInicio3Parameter = vFechaInicio3.HasValue ?
                new ObjectParameter("vFechaInicio3", vFechaInicio3) :
                new ObjectParameter("vFechaInicio3", typeof(System.DateTime));
    
            var vFechaFin3Parameter = vFechaFin3.HasValue ?
                new ObjectParameter("vFechaFin3", vFechaFin3) :
                new ObjectParameter("vFechaFin3", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarMascotasdeClientesFecha_Result>("usp_ListarMascotasdeClientesFecha", vCod_ClienteParameter, vEstado2Parameter, vFechaInicio3Parameter, vFechaFin3Parameter);
        }
    
        public virtual ObjectResult<usp_ListarMascotasdeClientesFechas2_Result> usp_ListarMascotasdeClientesFechas2(Nullable<int> vCod_Cliente, string vEstado2, Nullable<System.DateTime> vFechaInicio3, Nullable<System.DateTime> vFechaFin3)
        {
            var vCod_ClienteParameter = vCod_Cliente.HasValue ?
                new ObjectParameter("vCod_Cliente", vCod_Cliente) :
                new ObjectParameter("vCod_Cliente", typeof(int));
    
            var vEstado2Parameter = vEstado2 != null ?
                new ObjectParameter("vEstado2", vEstado2) :
                new ObjectParameter("vEstado2", typeof(string));
    
            var vFechaInicio3Parameter = vFechaInicio3.HasValue ?
                new ObjectParameter("vFechaInicio3", vFechaInicio3) :
                new ObjectParameter("vFechaInicio3", typeof(System.DateTime));
    
            var vFechaFin3Parameter = vFechaFin3.HasValue ?
                new ObjectParameter("vFechaFin3", vFechaFin3) :
                new ObjectParameter("vFechaFin3", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarMascotasdeClientesFechas2_Result>("usp_ListarMascotasdeClientesFechas2", vCod_ClienteParameter, vEstado2Parameter, vFechaInicio3Parameter, vFechaFin3Parameter);
        }
    
        public virtual ObjectResult<usp_TopAtencionesClientesMascotasAño2_Result> usp_TopAtencionesClientesMascotasAño2(Nullable<int> vaño)
        {
            var vañoParameter = vaño.HasValue ?
                new ObjectParameter("vaño", vaño) :
                new ObjectParameter("vaño", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TopAtencionesClientesMascotasAño2_Result>("usp_TopAtencionesClientesMascotasAño2", vañoParameter);
        }
    
        public virtual ObjectResult<usp_TopAtencionesMascotasAño2_Result> usp_TopAtencionesMascotasAño2(Nullable<int> vaño2)
        {
            var vaño2Parameter = vaño2.HasValue ?
                new ObjectParameter("vaño2", vaño2) :
                new ObjectParameter("vaño2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_TopAtencionesMascotasAño2_Result>("usp_TopAtencionesMascotasAño2", vaño2Parameter);
        }
    
        public virtual ObjectResult<usp_ListarVeterinario_Result> usp_ListarVeterinario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarVeterinario_Result>("usp_ListarVeterinario");
        }
    }
}
