//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWCF_Veterinaria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Det_Consulta
    {
        public int id_Det_consulta { get; set; }
        public int id_consulta { get; set; }
        public Nullable<int> cod_medicamento { get; set; }
        public string observaciones { get; set; }
        public string tratamiento { get; set; }
        public Nullable<System.DateTime> fec_registro { get; set; }
        public Nullable<System.DateTime> fec_Ult_Mod { get; set; }
        public string Usu_Ult_Mod { get; set; }
    
        public virtual Consulta Consulta { get; set; }
        public virtual Medicamento Medicamento { get; set; }
    }
}
