//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWCF_Veterinaria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string Login_Usuario { get; set; }
        public string pass_Usuario { get; set; }
        public Nullable<int> niv_Usuario { get; set; }
        public Nullable<int> est_Usuario { get; set; }
        public Nullable<System.DateTime> fec_Usuario { get; set; }
        public string Usu_Registro { get; set; }
        public Nullable<System.DateTime> fec_Ult_Mod { get; set; }
        public string Usu_Ult_Mod { get; set; }
    }
}
