//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWCF_Veterinaria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veterinario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Veterinario()
        {
            this.Consulta = new HashSet<Consulta>();
        }
    
        public int cod_veterinario { get; set; }
        public string nom_veterinario { get; set; }
        public string ape_veterinario { get; set; }
        public string Usu_Registro { get; set; }
        public Nullable<int> sueldo { get; set; }
        public Nullable<int> dni_vet { get; set; }
        public string foto_vet { get; set; }
        public Nullable<int> est_vet { get; set; }
        public string direccion { get; set; }
        public string tel_veterinario { get; set; }
        public Nullable<int> cod_especialidad { get; set; }
        public string id_ubigeo { get; set; }
        public Nullable<System.DateTime> fec_Ult_Mod { get; set; }
        public string Usu_Ult_Mod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consulta> Consulta { get; set; }
        public virtual Especialidad Especialidad { get; set; }
        public virtual Ubigeo Ubigeo { get; set; }
    }
}
