//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWCF_Veterinaria
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_VistaVeterinario
    {
        public int cod_veterinario { get; set; }
        public string nom_veterinario { get; set; }
        public string ape_veterinario { get; set; }
        public string Departamento { get; set; }
        public string Provincia { get; set; }
        public string dni_vet { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> sueldo { get; set; }
        public string Estado { get; set; }
        public string direccion { get; set; }
        public string tel_veterinario { get; set; }
    }
}
