//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWCF_Veterinaria
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_VistaConsulta
    {
        public int id_consulta { get; set; }
        public Nullable<System.DateTime> fec_consulta { get; set; }
        public Nullable<int> cod_mascota { get; set; }
        public int cod_cliente { get; set; }
        public Nullable<int> dni_cli { get; set; }
        public string tel_cliente { get; set; }
        public string departamento { get; set; }
        public string provincia { get; set; }
        public string distrito { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> est_consulta { get; set; }
        public string Estado { get; set; }
        public int cod_veterinario { get; set; }
        public string nom_veterinario { get; set; }
        public string ape_veterinario { get; set; }
        public string nom_mascota { get; set; }
        public string observaciones { get; set; }
        public string nom_cliente { get; set; }
        public string ape_Cliente { get; set; }
    }
}
