//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWCF_Veterinaria
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_VistaCliente
    {
        public int cod_cliente { get; set; }
        public Nullable<int> dni_cli { get; set; }
        public string Cliente { get; set; }
        public string dirección { get; set; }
        public string tel_cliente { get; set; }
        public Nullable<int> est_cli { get; set; }
        public Nullable<System.DateTime> fec_registro { get; set; }
        public string Estado { get; set; }
        public string Sexo { get; set; }
        public string departamento { get; set; }
        public string provincia { get; set; }
        public string distrito { get; set; }
    }
}
