//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows_Veterinario.ProxyEstadistica {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteEstadistica", Namespace="http://schemas.datacontract.org/2004/07/DemoWCF_Veterinaria")]
    [System.SerializableAttribute()]
    public partial class ClienteEstadistica : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ConsultasTotalesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ape_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_cliField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConsultasTotales {
            get {
                return this.ConsultasTotalesField;
            }
            set {
                if ((this.ConsultasTotalesField.Equals(value) != true)) {
                    this.ConsultasTotalesField = value;
                    this.RaisePropertyChanged("ConsultasTotales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ape_cli {
            get {
                return this.ape_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.ape_cliField, value) != true)) {
                    this.ape_cliField = value;
                    this.RaisePropertyChanged("ape_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_cli {
            get {
                return this.cod_cliField;
            }
            set {
                if ((this.cod_cliField.Equals(value) != true)) {
                    this.cod_cliField = value;
                    this.RaisePropertyChanged("cod_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_cli {
            get {
                return this.nom_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_cliField, value) != true)) {
                    this.nom_cliField = value;
                    this.RaisePropertyChanged("nom_cli");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MascotasEstadistica", Namespace="http://schemas.datacontract.org/2004/07/DemoWCF_Veterinaria")]
    [System.SerializableAttribute()]
    public partial class MascotasEstadistica : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ConsultasTotalesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_mascotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_mascotaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConsultasTotales {
            get {
                return this.ConsultasTotalesField;
            }
            set {
                if ((this.ConsultasTotalesField.Equals(value) != true)) {
                    this.ConsultasTotalesField = value;
                    this.RaisePropertyChanged("ConsultasTotales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_mascota {
            get {
                return this.cod_mascotaField;
            }
            set {
                if ((this.cod_mascotaField.Equals(value) != true)) {
                    this.cod_mascotaField = value;
                    this.RaisePropertyChanged("cod_mascota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_mascota {
            get {
                return this.nom_mascotaField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_mascotaField, value) != true)) {
                    this.nom_mascotaField = value;
                    this.RaisePropertyChanged("nom_mascota");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedicinaEstadistica", Namespace="http://schemas.datacontract.org/2004/07/DemoWCF_Veterinaria")]
    [System.SerializableAttribute()]
    public partial class MedicinaEstadistica : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadRecetadasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_medicamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string des_medicamentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadRecetadas {
            get {
                return this.CantidadRecetadasField;
            }
            set {
                if ((this.CantidadRecetadasField.Equals(value) != true)) {
                    this.CantidadRecetadasField = value;
                    this.RaisePropertyChanged("CantidadRecetadas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_medicamento {
            get {
                return this.cod_medicamentoField;
            }
            set {
                if ((this.cod_medicamentoField.Equals(value) != true)) {
                    this.cod_medicamentoField = value;
                    this.RaisePropertyChanged("cod_medicamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string des_medicamento {
            get {
                return this.des_medicamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.des_medicamentoField, value) != true)) {
                    this.des_medicamentoField = value;
                    this.RaisePropertyChanged("des_medicamento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultasEstadistica", Namespace="http://schemas.datacontract.org/2004/07/DemoWCF_Veterinaria")]
    [System.SerializableAttribute()]
    public partial class ConsultasEstadistica : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ConsultasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MontosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Consultas {
            get {
                return this.ConsultasField;
            }
            set {
                if ((this.ConsultasField.Equals(value) != true)) {
                    this.ConsultasField = value;
                    this.RaisePropertyChanged("Consultas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Montos {
            get {
                return this.MontosField;
            }
            set {
                if ((this.MontosField.Equals(value) != true)) {
                    this.MontosField = value;
                    this.RaisePropertyChanged("Montos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyEstadistica.IServicioEstadistica")]
    public interface IServicioEstadistica {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstadistica/TopAtencionesClientesMascotasXAño", ReplyAction="http://tempuri.org/IServicioEstadistica/TopAtencionesClientesMascotasXAñoResponse" +
            "")]
        Windows_Veterinario.ProxyEstadistica.ClienteEstadistica[] TopAtencionesClientesMascotasXAño(short año, short top);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstadistica/TopAtencionesClientesMascotasXAño", ReplyAction="http://tempuri.org/IServicioEstadistica/TopAtencionesClientesMascotasXAñoResponse" +
            "")]
        System.Threading.Tasks.Task<Windows_Veterinario.ProxyEstadistica.ClienteEstadistica[]> TopAtencionesClientesMascotasXAñoAsync(short año, short top);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstadistica/TopAtencionesMascotasXAño", ReplyAction="http://tempuri.org/IServicioEstadistica/TopAtencionesMascotasXAñoResponse")]
        Windows_Veterinario.ProxyEstadistica.MascotasEstadistica[] TopAtencionesMascotasXAño(short año, short top);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstadistica/TopAtencionesMascotasXAño", ReplyAction="http://tempuri.org/IServicioEstadistica/TopAtencionesMascotasXAñoResponse")]
        System.Threading.Tasks.Task<Windows_Veterinario.ProxyEstadistica.MascotasEstadistica[]> TopAtencionesMascotasXAñoAsync(short año, short top);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstadistica/TopMedicinasXAño", ReplyAction="http://tempuri.org/IServicioEstadistica/TopMedicinasXAñoResponse")]
        Windows_Veterinario.ProxyEstadistica.MedicinaEstadistica[] TopMedicinasXAño(short año, short top);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstadistica/TopMedicinasXAño", ReplyAction="http://tempuri.org/IServicioEstadistica/TopMedicinasXAñoResponse")]
        System.Threading.Tasks.Task<Windows_Veterinario.ProxyEstadistica.MedicinaEstadistica[]> TopMedicinasXAñoAsync(short año, short top);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstadistica/ConsultasXAño", ReplyAction="http://tempuri.org/IServicioEstadistica/ConsultasXAñoResponse")]
        Windows_Veterinario.ProxyEstadistica.ConsultasEstadistica[] ConsultasXAño(short año);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEstadistica/ConsultasXAño", ReplyAction="http://tempuri.org/IServicioEstadistica/ConsultasXAñoResponse")]
        System.Threading.Tasks.Task<Windows_Veterinario.ProxyEstadistica.ConsultasEstadistica[]> ConsultasXAñoAsync(short año);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioEstadisticaChannel : Windows_Veterinario.ProxyEstadistica.IServicioEstadistica, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioEstadisticaClient : System.ServiceModel.ClientBase<Windows_Veterinario.ProxyEstadistica.IServicioEstadistica>, Windows_Veterinario.ProxyEstadistica.IServicioEstadistica {
        
        public ServicioEstadisticaClient() {
        }
        
        public ServicioEstadisticaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioEstadisticaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEstadisticaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEstadisticaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Windows_Veterinario.ProxyEstadistica.ClienteEstadistica[] TopAtencionesClientesMascotasXAño(short año, short top) {
            return base.Channel.TopAtencionesClientesMascotasXAño(año, top);
        }
        
        public System.Threading.Tasks.Task<Windows_Veterinario.ProxyEstadistica.ClienteEstadistica[]> TopAtencionesClientesMascotasXAñoAsync(short año, short top) {
            return base.Channel.TopAtencionesClientesMascotasXAñoAsync(año, top);
        }
        
        public Windows_Veterinario.ProxyEstadistica.MascotasEstadistica[] TopAtencionesMascotasXAño(short año, short top) {
            return base.Channel.TopAtencionesMascotasXAño(año, top);
        }
        
        public System.Threading.Tasks.Task<Windows_Veterinario.ProxyEstadistica.MascotasEstadistica[]> TopAtencionesMascotasXAñoAsync(short año, short top) {
            return base.Channel.TopAtencionesMascotasXAñoAsync(año, top);
        }
        
        public Windows_Veterinario.ProxyEstadistica.MedicinaEstadistica[] TopMedicinasXAño(short año, short top) {
            return base.Channel.TopMedicinasXAño(año, top);
        }
        
        public System.Threading.Tasks.Task<Windows_Veterinario.ProxyEstadistica.MedicinaEstadistica[]> TopMedicinasXAñoAsync(short año, short top) {
            return base.Channel.TopMedicinasXAñoAsync(año, top);
        }
        
        public Windows_Veterinario.ProxyEstadistica.ConsultasEstadistica[] ConsultasXAño(short año) {
            return base.Channel.ConsultasXAño(año);
        }
        
        public System.Threading.Tasks.Task<Windows_Veterinario.ProxyEstadistica.ConsultasEstadistica[]> ConsultasXAñoAsync(short año) {
            return base.Channel.ConsultasXAñoAsync(año);
        }
    }
}
