//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows_Veterinario.ProxyConsulta {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaDC", Namespace="http://schemas.datacontract.org/2004/07/DemoWCF_Veterinaria")]
    [System.SerializableAttribute()]
    public partial class ConsultaDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ape_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_veterinarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fec_consultaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_consultaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_mascotaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ape_cliente {
            get {
                return this.ape_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ape_clienteField, value) != true)) {
                    this.ape_clienteField = value;
                    this.RaisePropertyChanged("ape_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_veterinario {
            get {
                return this.cod_veterinarioField;
            }
            set {
                if ((this.cod_veterinarioField.Equals(value) != true)) {
                    this.cod_veterinarioField = value;
                    this.RaisePropertyChanged("cod_veterinario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fec_consulta {
            get {
                return this.fec_consultaField;
            }
            set {
                if ((this.fec_consultaField.Equals(value) != true)) {
                    this.fec_consultaField = value;
                    this.RaisePropertyChanged("fec_consulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_consulta {
            get {
                return this.id_consultaField;
            }
            set {
                if ((this.id_consultaField.Equals(value) != true)) {
                    this.id_consultaField = value;
                    this.RaisePropertyChanged("id_consulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_cliente {
            get {
                return this.nom_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_clienteField, value) != true)) {
                    this.nom_clienteField = value;
                    this.RaisePropertyChanged("nom_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_mascota {
            get {
                return this.nom_mascotaField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_mascotaField, value) != true)) {
                    this.nom_mascotaField = value;
                    this.RaisePropertyChanged("nom_mascota");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaDCVet", Namespace="http://schemas.datacontract.org/2004/07/DemoWCF_Veterinaria")]
    [System.SerializableAttribute()]
    public partial class ConsultaDCVet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ape_veterinarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_veterinarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fec_consultaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_consultaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_mascotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_veterinarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ape_veterinario {
            get {
                return this.ape_veterinarioField;
            }
            set {
                if ((object.ReferenceEquals(this.ape_veterinarioField, value) != true)) {
                    this.ape_veterinarioField = value;
                    this.RaisePropertyChanged("ape_veterinario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_veterinario {
            get {
                return this.cod_veterinarioField;
            }
            set {
                if ((this.cod_veterinarioField.Equals(value) != true)) {
                    this.cod_veterinarioField = value;
                    this.RaisePropertyChanged("cod_veterinario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fec_consulta {
            get {
                return this.fec_consultaField;
            }
            set {
                if ((this.fec_consultaField.Equals(value) != true)) {
                    this.fec_consultaField = value;
                    this.RaisePropertyChanged("fec_consulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_consulta {
            get {
                return this.id_consultaField;
            }
            set {
                if ((this.id_consultaField.Equals(value) != true)) {
                    this.id_consultaField = value;
                    this.RaisePropertyChanged("id_consulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_mascota {
            get {
                return this.nom_mascotaField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_mascotaField, value) != true)) {
                    this.nom_mascotaField = value;
                    this.RaisePropertyChanged("nom_mascota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_veterinario {
            get {
                return this.nom_veterinarioField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_veterinarioField, value) != true)) {
                    this.nom_veterinarioField = value;
                    this.RaisePropertyChanged("nom_veterinario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaDCEsp", Namespace="http://schemas.datacontract.org/2004/07/DemoWCF_Veterinaria")]
    [System.SerializableAttribute()]
    public partial class ConsultaDCEsp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EspecieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short cod_espField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_mascotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_mascotaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Especie {
            get {
                return this.EspecieField;
            }
            set {
                if ((object.ReferenceEquals(this.EspecieField, value) != true)) {
                    this.EspecieField = value;
                    this.RaisePropertyChanged("Especie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short cod_esp {
            get {
                return this.cod_espField;
            }
            set {
                if ((this.cod_espField.Equals(value) != true)) {
                    this.cod_espField = value;
                    this.RaisePropertyChanged("cod_esp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_mascota {
            get {
                return this.cod_mascotaField;
            }
            set {
                if ((this.cod_mascotaField.Equals(value) != true)) {
                    this.cod_mascotaField = value;
                    this.RaisePropertyChanged("cod_mascota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_mascota {
            get {
                return this.nom_mascotaField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_mascotaField, value) != true)) {
                    this.nom_mascotaField = value;
                    this.RaisePropertyChanged("nom_mascota");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyConsulta.IServicioConsulta")]
    public interface IServicioConsulta {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/ListarConsultasMascotaFechas", ReplyAction="http://tempuri.org/IServicioConsulta/ListarConsultasMascotaFechasResponse")]
        Windows_Veterinario.ProxyConsulta.ConsultaDC[] ListarConsultasMascotaFechas(int strCodigo, System.DateTime fecini, System.DateTime fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/ListarConsultasMascotaFechas", ReplyAction="http://tempuri.org/IServicioConsulta/ListarConsultasMascotaFechasResponse")]
        System.Threading.Tasks.Task<Windows_Veterinario.ProxyConsulta.ConsultaDC[]> ListarConsultasMascotaFechasAsync(int strCodigo, System.DateTime fecini, System.DateTime fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/ListarConsultasVeterinarioFechas", ReplyAction="http://tempuri.org/IServicioConsulta/ListarConsultasVeterinarioFechasResponse")]
        Windows_Veterinario.ProxyConsulta.ConsultaDCVet[] ListarConsultasVeterinarioFechas(int strCodigo, string estado, System.DateTime fecini, System.DateTime fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/ListarConsultasVeterinarioFechas", ReplyAction="http://tempuri.org/IServicioConsulta/ListarConsultasVeterinarioFechasResponse")]
        System.Threading.Tasks.Task<Windows_Veterinario.ProxyConsulta.ConsultaDCVet[]> ListarConsultasVeterinarioFechasAsync(int strCodigo, string estado, System.DateTime fecini, System.DateTime fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/ListarMascotasPorEspecie", ReplyAction="http://tempuri.org/IServicioConsulta/ListarMascotasPorEspecieResponse")]
        Windows_Veterinario.ProxyConsulta.ConsultaDCEsp[] ListarMascotasPorEspecie(int strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/ListarMascotasPorEspecie", ReplyAction="http://tempuri.org/IServicioConsulta/ListarMascotasPorEspecieResponse")]
        System.Threading.Tasks.Task<Windows_Veterinario.ProxyConsulta.ConsultaDCEsp[]> ListarMascotasPorEspecieAsync(int strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/ListarConsultasClientesFechas", ReplyAction="http://tempuri.org/IServicioConsulta/ListarConsultasClientesFechasResponse")]
        Windows_Veterinario.ProxyConsulta.ConsultaDC[] ListarConsultasClientesFechas(int strCodigo, string estado, System.DateTime fecini, System.DateTime fecfin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsulta/ListarConsultasClientesFechas", ReplyAction="http://tempuri.org/IServicioConsulta/ListarConsultasClientesFechasResponse")]
        System.Threading.Tasks.Task<Windows_Veterinario.ProxyConsulta.ConsultaDC[]> ListarConsultasClientesFechasAsync(int strCodigo, string estado, System.DateTime fecini, System.DateTime fecfin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioConsultaChannel : Windows_Veterinario.ProxyConsulta.IServicioConsulta, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioConsultaClient : System.ServiceModel.ClientBase<Windows_Veterinario.ProxyConsulta.IServicioConsulta>, Windows_Veterinario.ProxyConsulta.IServicioConsulta {
        
        public ServicioConsultaClient() {
        }
        
        public ServicioConsultaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioConsultaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioConsultaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioConsultaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Windows_Veterinario.ProxyConsulta.ConsultaDC[] ListarConsultasMascotaFechas(int strCodigo, System.DateTime fecini, System.DateTime fecfin) {
            return base.Channel.ListarConsultasMascotaFechas(strCodigo, fecini, fecfin);
        }
        
        public System.Threading.Tasks.Task<Windows_Veterinario.ProxyConsulta.ConsultaDC[]> ListarConsultasMascotaFechasAsync(int strCodigo, System.DateTime fecini, System.DateTime fecfin) {
            return base.Channel.ListarConsultasMascotaFechasAsync(strCodigo, fecini, fecfin);
        }
        
        public Windows_Veterinario.ProxyConsulta.ConsultaDCVet[] ListarConsultasVeterinarioFechas(int strCodigo, string estado, System.DateTime fecini, System.DateTime fecfin) {
            return base.Channel.ListarConsultasVeterinarioFechas(strCodigo, estado, fecini, fecfin);
        }
        
        public System.Threading.Tasks.Task<Windows_Veterinario.ProxyConsulta.ConsultaDCVet[]> ListarConsultasVeterinarioFechasAsync(int strCodigo, string estado, System.DateTime fecini, System.DateTime fecfin) {
            return base.Channel.ListarConsultasVeterinarioFechasAsync(strCodigo, estado, fecini, fecfin);
        }
        
        public Windows_Veterinario.ProxyConsulta.ConsultaDCEsp[] ListarMascotasPorEspecie(int strCodigo) {
            return base.Channel.ListarMascotasPorEspecie(strCodigo);
        }
        
        public System.Threading.Tasks.Task<Windows_Veterinario.ProxyConsulta.ConsultaDCEsp[]> ListarMascotasPorEspecieAsync(int strCodigo) {
            return base.Channel.ListarMascotasPorEspecieAsync(strCodigo);
        }
        
        public Windows_Veterinario.ProxyConsulta.ConsultaDC[] ListarConsultasClientesFechas(int strCodigo, string estado, System.DateTime fecini, System.DateTime fecfin) {
            return base.Channel.ListarConsultasClientesFechas(strCodigo, estado, fecini, fecfin);
        }
        
        public System.Threading.Tasks.Task<Windows_Veterinario.ProxyConsulta.ConsultaDC[]> ListarConsultasClientesFechasAsync(int strCodigo, string estado, System.DateTime fecini, System.DateTime fecfin) {
            return base.Channel.ListarConsultasClientesFechasAsync(strCodigo, estado, fecini, fecfin);
        }
    }
}
