//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows_Veterinario.ProxyVeterinario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VeterinarioDC", Namespace="http://schemas.datacontract.org/2004/07/DemoWCF_Veterinaria")]
    [System.SerializableAttribute()]
    public partial class VeterinarioDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ape_veterinarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short cod_especialidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_veterinarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string des_especialidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int dni_vetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short est_vetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fec_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_veterinarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int sueldoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tel_veterinarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro {
            get {
                return this.Usu_RegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_RegistroField, value) != true)) {
                    this.Usu_RegistroField = value;
                    this.RaisePropertyChanged("Usu_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod {
            get {
                return this.Usu_Ult_ModField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_Ult_ModField, value) != true)) {
                    this.Usu_Ult_ModField = value;
                    this.RaisePropertyChanged("Usu_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ape_veterinario {
            get {
                return this.ape_veterinarioField;
            }
            set {
                if ((object.ReferenceEquals(this.ape_veterinarioField, value) != true)) {
                    this.ape_veterinarioField = value;
                    this.RaisePropertyChanged("ape_veterinario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short cod_especialidad {
            get {
                return this.cod_especialidadField;
            }
            set {
                if ((this.cod_especialidadField.Equals(value) != true)) {
                    this.cod_especialidadField = value;
                    this.RaisePropertyChanged("cod_especialidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_veterinario {
            get {
                return this.cod_veterinarioField;
            }
            set {
                if ((this.cod_veterinarioField.Equals(value) != true)) {
                    this.cod_veterinarioField = value;
                    this.RaisePropertyChanged("cod_veterinario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string des_especialidad {
            get {
                return this.des_especialidadField;
            }
            set {
                if ((object.ReferenceEquals(this.des_especialidadField, value) != true)) {
                    this.des_especialidadField = value;
                    this.RaisePropertyChanged("des_especialidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int dni_vet {
            get {
                return this.dni_vetField;
            }
            set {
                if ((this.dni_vetField.Equals(value) != true)) {
                    this.dni_vetField = value;
                    this.RaisePropertyChanged("dni_vet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short est_vet {
            get {
                return this.est_vetField;
            }
            set {
                if ((this.est_vetField.Equals(value) != true)) {
                    this.est_vetField = value;
                    this.RaisePropertyChanged("est_vet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fec_Ult_Mod {
            get {
                return this.fec_Ult_ModField;
            }
            set {
                if ((this.fec_Ult_ModField.Equals(value) != true)) {
                    this.fec_Ult_ModField = value;
                    this.RaisePropertyChanged("fec_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string foto {
            get {
                return this.fotoField;
            }
            set {
                if ((object.ReferenceEquals(this.fotoField, value) != true)) {
                    this.fotoField = value;
                    this.RaisePropertyChanged("foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_veterinario {
            get {
                return this.nom_veterinarioField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_veterinarioField, value) != true)) {
                    this.nom_veterinarioField = value;
                    this.RaisePropertyChanged("nom_veterinario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int sueldo {
            get {
                return this.sueldoField;
            }
            set {
                if ((this.sueldoField.Equals(value) != true)) {
                    this.sueldoField = value;
                    this.RaisePropertyChanged("sueldo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tel_veterinario {
            get {
                return this.tel_veterinarioField;
            }
            set {
                if ((object.ReferenceEquals(this.tel_veterinarioField, value) != true)) {
                    this.tel_veterinarioField = value;
                    this.RaisePropertyChanged("tel_veterinario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyVeterinario.IServicioVeterinario")]
    public interface IServicioVeterinario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVeterinario/ConsultarVeterinario", ReplyAction="http://tempuri.org/IServicioVeterinario/ConsultarVeterinarioResponse")]
        Windows_Veterinario.ProxyVeterinario.VeterinarioDC ConsultarVeterinario(int strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVeterinario/ConsultarVeterinario", ReplyAction="http://tempuri.org/IServicioVeterinario/ConsultarVeterinarioResponse")]
        System.Threading.Tasks.Task<Windows_Veterinario.ProxyVeterinario.VeterinarioDC> ConsultarVeterinarioAsync(int strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVeterinario/ListarVeterinario", ReplyAction="http://tempuri.org/IServicioVeterinario/ListarVeterinarioResponse")]
        Windows_Veterinario.ProxyVeterinario.VeterinarioDC[] ListarVeterinario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioVeterinario/ListarVeterinario", ReplyAction="http://tempuri.org/IServicioVeterinario/ListarVeterinarioResponse")]
        System.Threading.Tasks.Task<Windows_Veterinario.ProxyVeterinario.VeterinarioDC[]> ListarVeterinarioAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioVeterinarioChannel : Windows_Veterinario.ProxyVeterinario.IServicioVeterinario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioVeterinarioClient : System.ServiceModel.ClientBase<Windows_Veterinario.ProxyVeterinario.IServicioVeterinario>, Windows_Veterinario.ProxyVeterinario.IServicioVeterinario {
        
        public ServicioVeterinarioClient() {
        }
        
        public ServicioVeterinarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioVeterinarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioVeterinarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioVeterinarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Windows_Veterinario.ProxyVeterinario.VeterinarioDC ConsultarVeterinario(int strCodigo) {
            return base.Channel.ConsultarVeterinario(strCodigo);
        }
        
        public System.Threading.Tasks.Task<Windows_Veterinario.ProxyVeterinario.VeterinarioDC> ConsultarVeterinarioAsync(int strCodigo) {
            return base.Channel.ConsultarVeterinarioAsync(strCodigo);
        }
        
        public Windows_Veterinario.ProxyVeterinario.VeterinarioDC[] ListarVeterinario() {
            return base.Channel.ListarVeterinario();
        }
        
        public System.Threading.Tasks.Task<Windows_Veterinario.ProxyVeterinario.VeterinarioDC[]> ListarVeterinarioAsync() {
            return base.Channel.ListarVeterinarioAsync();
        }
    }
}
