//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows_Veterinario.ProxyMascota {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MascotaDC", Namespace="http://schemas.datacontract.org/2004/07/DemoWCF_Veterinaria")]
    [System.SerializableAttribute()]
    public partial class MascotaDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ape_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short cod_espField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_mascotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string colorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string des_espField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short est_mascotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fec_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fec_nacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] fotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_mascotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sexoLitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod {
            get {
                return this.Usu_Ult_ModField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_Ult_ModField, value) != true)) {
                    this.Usu_Ult_ModField = value;
                    this.RaisePropertyChanged("Usu_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ape_cliente {
            get {
                return this.ape_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ape_clienteField, value) != true)) {
                    this.ape_clienteField = value;
                    this.RaisePropertyChanged("ape_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_cliente {
            get {
                return this.cod_clienteField;
            }
            set {
                if ((this.cod_clienteField.Equals(value) != true)) {
                    this.cod_clienteField = value;
                    this.RaisePropertyChanged("cod_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short cod_esp {
            get {
                return this.cod_espField;
            }
            set {
                if ((this.cod_espField.Equals(value) != true)) {
                    this.cod_espField = value;
                    this.RaisePropertyChanged("cod_esp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_mascota {
            get {
                return this.cod_mascotaField;
            }
            set {
                if ((this.cod_mascotaField.Equals(value) != true)) {
                    this.cod_mascotaField = value;
                    this.RaisePropertyChanged("cod_mascota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string color {
            get {
                return this.colorField;
            }
            set {
                if ((object.ReferenceEquals(this.colorField, value) != true)) {
                    this.colorField = value;
                    this.RaisePropertyChanged("color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string des_esp {
            get {
                return this.des_espField;
            }
            set {
                if ((object.ReferenceEquals(this.des_espField, value) != true)) {
                    this.des_espField = value;
                    this.RaisePropertyChanged("des_esp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short est_mascota {
            get {
                return this.est_mascotaField;
            }
            set {
                if ((this.est_mascotaField.Equals(value) != true)) {
                    this.est_mascotaField = value;
                    this.RaisePropertyChanged("est_mascota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fec_Ult_Mod {
            get {
                return this.fec_Ult_ModField;
            }
            set {
                if ((this.fec_Ult_ModField.Equals(value) != true)) {
                    this.fec_Ult_ModField = value;
                    this.RaisePropertyChanged("fec_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fec_nacimiento {
            get {
                return this.fec_nacimientoField;
            }
            set {
                if ((this.fec_nacimientoField.Equals(value) != true)) {
                    this.fec_nacimientoField = value;
                    this.RaisePropertyChanged("fec_nacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                if ((object.ReferenceEquals(this.fotoField, value) != true)) {
                    this.fotoField = value;
                    this.RaisePropertyChanged("foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_cliente {
            get {
                return this.nom_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_clienteField, value) != true)) {
                    this.nom_clienteField = value;
                    this.RaisePropertyChanged("nom_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_mascota {
            get {
                return this.nom_mascotaField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_mascotaField, value) != true)) {
                    this.nom_mascotaField = value;
                    this.RaisePropertyChanged("nom_mascota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                if ((object.ReferenceEquals(this.sexoField, value) != true)) {
                    this.sexoField = value;
                    this.RaisePropertyChanged("sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sexoLit {
            get {
                return this.sexoLitField;
            }
            set {
                if ((object.ReferenceEquals(this.sexoLitField, value) != true)) {
                    this.sexoLitField = value;
                    this.RaisePropertyChanged("sexoLit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MascotaInsertar", Namespace="http://schemas.datacontract.org/2004/07/DemoWCF_Veterinaria")]
    [System.SerializableAttribute()]
    public partial class MascotaInsertar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ape_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short cod_espField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string colorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short est_mascotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fec_nacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] fotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_mascotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ape_cliente {
            get {
                return this.ape_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ape_clienteField, value) != true)) {
                    this.ape_clienteField = value;
                    this.RaisePropertyChanged("ape_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_cliente {
            get {
                return this.cod_clienteField;
            }
            set {
                if ((this.cod_clienteField.Equals(value) != true)) {
                    this.cod_clienteField = value;
                    this.RaisePropertyChanged("cod_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short cod_esp {
            get {
                return this.cod_espField;
            }
            set {
                if ((this.cod_espField.Equals(value) != true)) {
                    this.cod_espField = value;
                    this.RaisePropertyChanged("cod_esp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string color {
            get {
                return this.colorField;
            }
            set {
                if ((object.ReferenceEquals(this.colorField, value) != true)) {
                    this.colorField = value;
                    this.RaisePropertyChanged("color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short est_mascota {
            get {
                return this.est_mascotaField;
            }
            set {
                if ((this.est_mascotaField.Equals(value) != true)) {
                    this.est_mascotaField = value;
                    this.RaisePropertyChanged("est_mascota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fec_nacimiento {
            get {
                return this.fec_nacimientoField;
            }
            set {
                if ((this.fec_nacimientoField.Equals(value) != true)) {
                    this.fec_nacimientoField = value;
                    this.RaisePropertyChanged("fec_nacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                if ((object.ReferenceEquals(this.fotoField, value) != true)) {
                    this.fotoField = value;
                    this.RaisePropertyChanged("foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_cliente {
            get {
                return this.nom_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_clienteField, value) != true)) {
                    this.nom_clienteField = value;
                    this.RaisePropertyChanged("nom_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_mascota {
            get {
                return this.nom_mascotaField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_mascotaField, value) != true)) {
                    this.nom_mascotaField = value;
                    this.RaisePropertyChanged("nom_mascota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                if ((object.ReferenceEquals(this.sexoField, value) != true)) {
                    this.sexoField = value;
                    this.RaisePropertyChanged("sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MascotaActualizar", Namespace="http://schemas.datacontract.org/2004/07/DemoWCF_Veterinaria")]
    [System.SerializableAttribute()]
    public partial class MascotaActualizar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ape_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short cod_espField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_mascotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string colorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short est_mascotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fec_nacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] fotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_mascotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod {
            get {
                return this.Usu_Ult_ModField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_Ult_ModField, value) != true)) {
                    this.Usu_Ult_ModField = value;
                    this.RaisePropertyChanged("Usu_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ape_cliente {
            get {
                return this.ape_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ape_clienteField, value) != true)) {
                    this.ape_clienteField = value;
                    this.RaisePropertyChanged("ape_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_cliente {
            get {
                return this.cod_clienteField;
            }
            set {
                if ((this.cod_clienteField.Equals(value) != true)) {
                    this.cod_clienteField = value;
                    this.RaisePropertyChanged("cod_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short cod_esp {
            get {
                return this.cod_espField;
            }
            set {
                if ((this.cod_espField.Equals(value) != true)) {
                    this.cod_espField = value;
                    this.RaisePropertyChanged("cod_esp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_mascota {
            get {
                return this.cod_mascotaField;
            }
            set {
                if ((this.cod_mascotaField.Equals(value) != true)) {
                    this.cod_mascotaField = value;
                    this.RaisePropertyChanged("cod_mascota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string color {
            get {
                return this.colorField;
            }
            set {
                if ((object.ReferenceEquals(this.colorField, value) != true)) {
                    this.colorField = value;
                    this.RaisePropertyChanged("color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short est_mascota {
            get {
                return this.est_mascotaField;
            }
            set {
                if ((this.est_mascotaField.Equals(value) != true)) {
                    this.est_mascotaField = value;
                    this.RaisePropertyChanged("est_mascota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fec_nacimiento {
            get {
                return this.fec_nacimientoField;
            }
            set {
                if ((this.fec_nacimientoField.Equals(value) != true)) {
                    this.fec_nacimientoField = value;
                    this.RaisePropertyChanged("fec_nacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                if ((object.ReferenceEquals(this.fotoField, value) != true)) {
                    this.fotoField = value;
                    this.RaisePropertyChanged("foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_cliente {
            get {
                return this.nom_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_clienteField, value) != true)) {
                    this.nom_clienteField = value;
                    this.RaisePropertyChanged("nom_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_mascota {
            get {
                return this.nom_mascotaField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_mascotaField, value) != true)) {
                    this.nom_mascotaField = value;
                    this.RaisePropertyChanged("nom_mascota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                if ((object.ReferenceEquals(this.sexoField, value) != true)) {
                    this.sexoField = value;
                    this.RaisePropertyChanged("sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EspecieDC", Namespace="http://schemas.datacontract.org/2004/07/DemoWCF_Veterinaria")]
    [System.SerializableAttribute()]
    public partial class EspecieDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_espField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string des_espField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_esp {
            get {
                return this.cod_espField;
            }
            set {
                if ((this.cod_espField.Equals(value) != true)) {
                    this.cod_espField = value;
                    this.RaisePropertyChanged("cod_esp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string des_esp {
            get {
                return this.des_espField;
            }
            set {
                if ((object.ReferenceEquals(this.des_espField, value) != true)) {
                    this.des_espField = value;
                    this.RaisePropertyChanged("des_esp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyMascota.IServicioMascota")]
    public interface IServicioMascota {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMascota/ConsultarMascota", ReplyAction="http://tempuri.org/IServicioMascota/ConsultarMascotaResponse")]
        Windows_Veterinario.ProxyMascota.MascotaDC ConsultarMascota(int strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMascota/ConsultarMascota", ReplyAction="http://tempuri.org/IServicioMascota/ConsultarMascotaResponse")]
        System.Threading.Tasks.Task<Windows_Veterinario.ProxyMascota.MascotaDC> ConsultarMascotaAsync(int strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMascota/InsertarMascota", ReplyAction="http://tempuri.org/IServicioMascota/InsertarMascotaResponse")]
        bool InsertarMascota(Windows_Veterinario.ProxyMascota.MascotaInsertar objMascotaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMascota/InsertarMascota", ReplyAction="http://tempuri.org/IServicioMascota/InsertarMascotaResponse")]
        System.Threading.Tasks.Task<bool> InsertarMascotaAsync(Windows_Veterinario.ProxyMascota.MascotaInsertar objMascotaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMascota/ActualizarMascota", ReplyAction="http://tempuri.org/IServicioMascota/ActualizarMascotaResponse")]
        bool ActualizarMascota(Windows_Veterinario.ProxyMascota.MascotaActualizar objMascotaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMascota/ActualizarMascota", ReplyAction="http://tempuri.org/IServicioMascota/ActualizarMascotaResponse")]
        System.Threading.Tasks.Task<bool> ActualizarMascotaAsync(Windows_Veterinario.ProxyMascota.MascotaActualizar objMascotaDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMascota/EliminarMascota", ReplyAction="http://tempuri.org/IServicioMascota/EliminarMascotaResponse")]
        bool EliminarMascota(int strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMascota/EliminarMascota", ReplyAction="http://tempuri.org/IServicioMascota/EliminarMascotaResponse")]
        System.Threading.Tasks.Task<bool> EliminarMascotaAsync(int strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMascota/ListarMascota", ReplyAction="http://tempuri.org/IServicioMascota/ListarMascotaResponse")]
        Windows_Veterinario.ProxyMascota.MascotaDC[] ListarMascota();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMascota/ListarMascota", ReplyAction="http://tempuri.org/IServicioMascota/ListarMascotaResponse")]
        System.Threading.Tasks.Task<Windows_Veterinario.ProxyMascota.MascotaDC[]> ListarMascotaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMascota/ListarEspecie", ReplyAction="http://tempuri.org/IServicioMascota/ListarEspecieResponse")]
        Windows_Veterinario.ProxyMascota.EspecieDC[] ListarEspecie();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMascota/ListarEspecie", ReplyAction="http://tempuri.org/IServicioMascota/ListarEspecieResponse")]
        System.Threading.Tasks.Task<Windows_Veterinario.ProxyMascota.EspecieDC[]> ListarEspecieAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioMascotaChannel : Windows_Veterinario.ProxyMascota.IServicioMascota, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioMascotaClient : System.ServiceModel.ClientBase<Windows_Veterinario.ProxyMascota.IServicioMascota>, Windows_Veterinario.ProxyMascota.IServicioMascota {
        
        public ServicioMascotaClient() {
        }
        
        public ServicioMascotaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioMascotaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioMascotaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioMascotaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Windows_Veterinario.ProxyMascota.MascotaDC ConsultarMascota(int strCodigo) {
            return base.Channel.ConsultarMascota(strCodigo);
        }
        
        public System.Threading.Tasks.Task<Windows_Veterinario.ProxyMascota.MascotaDC> ConsultarMascotaAsync(int strCodigo) {
            return base.Channel.ConsultarMascotaAsync(strCodigo);
        }
        
        public bool InsertarMascota(Windows_Veterinario.ProxyMascota.MascotaInsertar objMascotaDC) {
            return base.Channel.InsertarMascota(objMascotaDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarMascotaAsync(Windows_Veterinario.ProxyMascota.MascotaInsertar objMascotaDC) {
            return base.Channel.InsertarMascotaAsync(objMascotaDC);
        }
        
        public bool ActualizarMascota(Windows_Veterinario.ProxyMascota.MascotaActualizar objMascotaDC) {
            return base.Channel.ActualizarMascota(objMascotaDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarMascotaAsync(Windows_Veterinario.ProxyMascota.MascotaActualizar objMascotaDC) {
            return base.Channel.ActualizarMascotaAsync(objMascotaDC);
        }
        
        public bool EliminarMascota(int strCodigo) {
            return base.Channel.EliminarMascota(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarMascotaAsync(int strCodigo) {
            return base.Channel.EliminarMascotaAsync(strCodigo);
        }
        
        public Windows_Veterinario.ProxyMascota.MascotaDC[] ListarMascota() {
            return base.Channel.ListarMascota();
        }
        
        public System.Threading.Tasks.Task<Windows_Veterinario.ProxyMascota.MascotaDC[]> ListarMascotaAsync() {
            return base.Channel.ListarMascotaAsync();
        }
        
        public Windows_Veterinario.ProxyMascota.EspecieDC[] ListarEspecie() {
            return base.Channel.ListarEspecie();
        }
        
        public System.Threading.Tasks.Task<Windows_Veterinario.ProxyMascota.EspecieDC[]> ListarEspecieAsync() {
            return base.Channel.ListarEspecieAsync();
        }
    }
}
