//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows_Veterinario.ProxyCliente {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteDC", Namespace="http://schemas.datacontract.org/2004/07/DemoWCF_Veterinaria")]
    [System.SerializableAttribute()]
    public partial class ClienteDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ape_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int dni_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short est_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fec_registroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_UbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string num_regField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sexo_litField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tel_clienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro {
            get {
                return this.Usu_RegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_RegistroField, value) != true)) {
                    this.Usu_RegistroField = value;
                    this.RaisePropertyChanged("Usu_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod {
            get {
                return this.Usu_Ult_ModField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_Ult_ModField, value) != true)) {
                    this.Usu_Ult_ModField = value;
                    this.RaisePropertyChanged("Usu_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ape_cliente {
            get {
                return this.ape_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ape_clienteField, value) != true)) {
                    this.ape_clienteField = value;
                    this.RaisePropertyChanged("ape_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_cliente {
            get {
                return this.cod_clienteField;
            }
            set {
                if ((this.cod_clienteField.Equals(value) != true)) {
                    this.cod_clienteField = value;
                    this.RaisePropertyChanged("cod_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int dni_cli {
            get {
                return this.dni_cliField;
            }
            set {
                if ((this.dni_cliField.Equals(value) != true)) {
                    this.dni_cliField = value;
                    this.RaisePropertyChanged("dni_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short est_cli {
            get {
                return this.est_cliField;
            }
            set {
                if ((this.est_cliField.Equals(value) != true)) {
                    this.est_cliField = value;
                    this.RaisePropertyChanged("est_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fec_registro {
            get {
                return this.fec_registroField;
            }
            set {
                if ((this.fec_registroField.Equals(value) != true)) {
                    this.fec_registroField = value;
                    this.RaisePropertyChanged("fec_registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_Ubigeo {
            get {
                return this.id_UbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.id_UbigeoField, value) != true)) {
                    this.id_UbigeoField = value;
                    this.RaisePropertyChanged("id_Ubigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_cliente {
            get {
                return this.nom_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_clienteField, value) != true)) {
                    this.nom_clienteField = value;
                    this.RaisePropertyChanged("nom_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string num_reg {
            get {
                return this.num_regField;
            }
            set {
                if ((object.ReferenceEquals(this.num_regField, value) != true)) {
                    this.num_regField = value;
                    this.RaisePropertyChanged("num_reg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                if ((object.ReferenceEquals(this.sexoField, value) != true)) {
                    this.sexoField = value;
                    this.RaisePropertyChanged("sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sexo_lit {
            get {
                return this.sexo_litField;
            }
            set {
                if ((object.ReferenceEquals(this.sexo_litField, value) != true)) {
                    this.sexo_litField = value;
                    this.RaisePropertyChanged("sexo_lit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tel_cliente {
            get {
                return this.tel_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.tel_clienteField, value) != true)) {
                    this.tel_clienteField = value;
                    this.RaisePropertyChanged("tel_cliente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteInsertar", Namespace="http://schemas.datacontract.org/2004/07/DemoWCF_Veterinaria")]
    [System.SerializableAttribute()]
    public partial class ClienteInsertar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ape_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int dni_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short est_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_UbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tel_clienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro {
            get {
                return this.Usu_RegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_RegistroField, value) != true)) {
                    this.Usu_RegistroField = value;
                    this.RaisePropertyChanged("Usu_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ape_cliente {
            get {
                return this.ape_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ape_clienteField, value) != true)) {
                    this.ape_clienteField = value;
                    this.RaisePropertyChanged("ape_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int dni_cli {
            get {
                return this.dni_cliField;
            }
            set {
                if ((this.dni_cliField.Equals(value) != true)) {
                    this.dni_cliField = value;
                    this.RaisePropertyChanged("dni_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short est_cli {
            get {
                return this.est_cliField;
            }
            set {
                if ((this.est_cliField.Equals(value) != true)) {
                    this.est_cliField = value;
                    this.RaisePropertyChanged("est_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_Ubigeo {
            get {
                return this.id_UbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.id_UbigeoField, value) != true)) {
                    this.id_UbigeoField = value;
                    this.RaisePropertyChanged("id_Ubigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_cliente {
            get {
                return this.nom_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_clienteField, value) != true)) {
                    this.nom_clienteField = value;
                    this.RaisePropertyChanged("nom_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                if ((object.ReferenceEquals(this.sexoField, value) != true)) {
                    this.sexoField = value;
                    this.RaisePropertyChanged("sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tel_cliente {
            get {
                return this.tel_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.tel_clienteField, value) != true)) {
                    this.tel_clienteField = value;
                    this.RaisePropertyChanged("tel_cliente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteActualizar", Namespace="http://schemas.datacontract.org/2004/07/DemoWCF_Veterinaria")]
    [System.SerializableAttribute()]
    public partial class ClienteActualizar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ape_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int dni_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short est_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string id_UbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nom_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string num_regField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tel_clienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod {
            get {
                return this.Usu_Ult_ModField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_Ult_ModField, value) != true)) {
                    this.Usu_Ult_ModField = value;
                    this.RaisePropertyChanged("Usu_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ape_cliente {
            get {
                return this.ape_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ape_clienteField, value) != true)) {
                    this.ape_clienteField = value;
                    this.RaisePropertyChanged("ape_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_cliente {
            get {
                return this.cod_clienteField;
            }
            set {
                if ((this.cod_clienteField.Equals(value) != true)) {
                    this.cod_clienteField = value;
                    this.RaisePropertyChanged("cod_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int dni_cli {
            get {
                return this.dni_cliField;
            }
            set {
                if ((this.dni_cliField.Equals(value) != true)) {
                    this.dni_cliField = value;
                    this.RaisePropertyChanged("dni_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short est_cli {
            get {
                return this.est_cliField;
            }
            set {
                if ((this.est_cliField.Equals(value) != true)) {
                    this.est_cliField = value;
                    this.RaisePropertyChanged("est_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id_Ubigeo {
            get {
                return this.id_UbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.id_UbigeoField, value) != true)) {
                    this.id_UbigeoField = value;
                    this.RaisePropertyChanged("id_Ubigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom_cliente {
            get {
                return this.nom_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.nom_clienteField, value) != true)) {
                    this.nom_clienteField = value;
                    this.RaisePropertyChanged("nom_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string num_reg {
            get {
                return this.num_regField;
            }
            set {
                if ((object.ReferenceEquals(this.num_regField, value) != true)) {
                    this.num_regField = value;
                    this.RaisePropertyChanged("num_reg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                if ((object.ReferenceEquals(this.sexoField, value) != true)) {
                    this.sexoField = value;
                    this.RaisePropertyChanged("sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tel_cliente {
            get {
                return this.tel_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.tel_clienteField, value) != true)) {
                    this.tel_clienteField = value;
                    this.RaisePropertyChanged("tel_cliente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCliente.IServicioCliente")]
    public interface IServicioCliente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ConsultarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ConsultarClienteResponse")]
        Windows_Veterinario.ProxyCliente.ClienteDC ConsultarCliente(int strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ConsultarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ConsultarClienteResponse")]
        System.Threading.Tasks.Task<Windows_Veterinario.ProxyCliente.ClienteDC> ConsultarClienteAsync(int strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/InsertarCliente", ReplyAction="http://tempuri.org/IServicioCliente/InsertarClienteResponse")]
        bool InsertarCliente(Windows_Veterinario.ProxyCliente.ClienteInsertar objClienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/InsertarCliente", ReplyAction="http://tempuri.org/IServicioCliente/InsertarClienteResponse")]
        System.Threading.Tasks.Task<bool> InsertarClienteAsync(Windows_Veterinario.ProxyCliente.ClienteInsertar objClienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ActualizarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ActualizarClienteResponse")]
        bool ActualizarCliente(Windows_Veterinario.ProxyCliente.ClienteActualizar objClienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ActualizarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ActualizarClienteResponse")]
        System.Threading.Tasks.Task<bool> ActualizarClienteAsync(Windows_Veterinario.ProxyCliente.ClienteActualizar objClienteDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/EliminarCliente", ReplyAction="http://tempuri.org/IServicioCliente/EliminarClienteResponse")]
        bool EliminarCliente(int strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/EliminarCliente", ReplyAction="http://tempuri.org/IServicioCliente/EliminarClienteResponse")]
        System.Threading.Tasks.Task<bool> EliminarClienteAsync(int strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ListarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ListarClienteResponse")]
        Windows_Veterinario.ProxyCliente.ClienteDC[] ListarCliente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/ListarCliente", ReplyAction="http://tempuri.org/IServicioCliente/ListarClienteResponse")]
        System.Threading.Tasks.Task<Windows_Veterinario.ProxyCliente.ClienteDC[]> ListarClienteAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioClienteChannel : Windows_Veterinario.ProxyCliente.IServicioCliente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClienteClient : System.ServiceModel.ClientBase<Windows_Veterinario.ProxyCliente.IServicioCliente>, Windows_Veterinario.ProxyCliente.IServicioCliente {
        
        public ServicioClienteClient() {
        }
        
        public ServicioClienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Windows_Veterinario.ProxyCliente.ClienteDC ConsultarCliente(int strCodigo) {
            return base.Channel.ConsultarCliente(strCodigo);
        }
        
        public System.Threading.Tasks.Task<Windows_Veterinario.ProxyCliente.ClienteDC> ConsultarClienteAsync(int strCodigo) {
            return base.Channel.ConsultarClienteAsync(strCodigo);
        }
        
        public bool InsertarCliente(Windows_Veterinario.ProxyCliente.ClienteInsertar objClienteDC) {
            return base.Channel.InsertarCliente(objClienteDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarClienteAsync(Windows_Veterinario.ProxyCliente.ClienteInsertar objClienteDC) {
            return base.Channel.InsertarClienteAsync(objClienteDC);
        }
        
        public bool ActualizarCliente(Windows_Veterinario.ProxyCliente.ClienteActualizar objClienteDC) {
            return base.Channel.ActualizarCliente(objClienteDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarClienteAsync(Windows_Veterinario.ProxyCliente.ClienteActualizar objClienteDC) {
            return base.Channel.ActualizarClienteAsync(objClienteDC);
        }
        
        public bool EliminarCliente(int strCodigo) {
            return base.Channel.EliminarCliente(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarClienteAsync(int strCodigo) {
            return base.Channel.EliminarClienteAsync(strCodigo);
        }
        
        public Windows_Veterinario.ProxyCliente.ClienteDC[] ListarCliente() {
            return base.Channel.ListarCliente();
        }
        
        public System.Threading.Tasks.Task<Windows_Veterinario.ProxyCliente.ClienteDC[]> ListarClienteAsync() {
            return base.Channel.ListarClienteAsync();
        }
    }
}
